### PR TITLE
NARA Mapping Redux

### PR DESCRIPTION
**Pull request by no-reply**
Supersedes #14.

Note that this is heavily rebased/squashed. I've left my commits distinct to make it easier to see what I've changed. I suspect we'll either want to squash to one commit or re-introduce some of the intermediary commits from @markbreedlove.

### CODE REVIEW

**Comment by no-reply** [comment]
After discussion w/ @guegueng, we decided to punt the `Most Recent` issue for contributor/creator fields. (see: https://github.com/dpla/heidrun-mappings/pull/49/files#diff-2dc9e1a949d2a5e9d0999c268b86dfcfR135)

The vast majority of records seem to not display this behavior (I haven't been able to find any exemplars); and it seems like something we could root out in a second round if it turns out to be a problem.

**Comment by markbreedlove** [comment]
Thanks, @no-reply. I think this is all good and have no suggestions.

I'll give @anarchivist a chance to respond; otherwise, I'd be happy to merge it. Assuming the `[fixup]` wants to be squashed -- perhaps others, too.

**Comment by no-reply** [comment]
Squashed down to two commits.

**Comment by anarchivist** [comment]
:rocket:

**Pull request merged**
