### PR TITLE
Add missing originalRecord property declarations

### PR DESCRIPTION
**Pull request by anarchivist**

### CODE REVIEW

**Comment by markbreedlove** [comment]
This looks good to me. Should anyone else review it? It will help to get some QA done which will determine next steps with various things.

**Comment by moltude** [comment]
It looked good to me and I put the same fix into the feature/pa-mapping branch

**Comment by markbreedlove** [comment]
@no-reply @anarchivist: I'm inclined to merge this if nobody objects.

**Comment by no-reply** [comment]
:+1:

**Pull request merged**
