### PR TITLE
Update date and subject for ESDN

### PR DESCRIPTION
**Pull request by no-reply**
@guegueng, @rudeamy, and @anarchivist may want to take a quick look.

### CODE REVIEW

**Comment by guegueng** [comment]
looks good to me

**Comment by anarchivist** [comment]
:+1: :squash:?

**Comment by no-reply** [comment]
I'm okay with leaving these as two commits. Thoughts? I squashed my syntax/style changes into 8086829.

**Comment by anarchivist** [comment]
:statue_of_liberty:

**Pull request merged**
