### PR TITLE
TN mapping updates

### PR DESCRIPTION
**Pull request by guegueng**
updates based on QA. See pivotal story for list of all the changes that need to be made to the mapping. I have done 5 of 8 total

### CODE REVIEW

**Comment by no-reply** [comment]
@guegueng Are there more known changes needed here? I'm in the process of running some records through for spot-check.

**Comment by guegueng** [comment]
I don't see the changes that need to be made to spatial and type per the comments here: https://www.pivotaltracker.com/n/projects/1172184/stories/97566468

**Comment by no-reply** [comment]
I think this mapping deals with all the issues discussed.

**Comment by anarchivist** [comment]
Previous comments were on commit dc7f7e22b3825a2d5edc0f84c8677bff0f88ea48, which has now been squashed.

**Pull request merged**
